### ISSUE TITLE
Published version 1.0.0 has an empty wheel

### ISSUE THREAD

**Issue by andrew-christianson** [toumorokoshi/deepmerge#14]
The version published yesterday has an empty wheel, but a valid source distribution.  This causes problems for downstream dependents, since installing deepmerge appears to succeed, but does not actually install the package

```sh
 $ curl -O https://files.pythonhosted.org/packages/83/fb/de90c82423bc34c7a3f529fbc1e46f5212e2e1333b9586994c02518023bb/deepmerge-1.0.0-py3-none-any.whl

$ unzip -l deepmerge-1.0.0-py3-none-any.whl
Archive:  deepmerge-1.0.0-py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
     1072  12-18-2021 06:34   deepmerge-1.0.0.dist-info/LICENSE
     1901  12-18-2021 06:34   deepmerge-1.0.0.dist-info/METADATA
       92  12-18-2021 06:34   deepmerge-1.0.0.dist-info/WHEEL
        1  12-18-2021 06:34   deepmerge-1.0.0.dist-info/top_level.txt
      395  12-18-2021 06:34   deepmerge-1.0.0.dist-info/RECORD
---------                     -------
     3461                     5 files
```

**Comment by andrew-christianson** [comment]
Pretty sure you just need 

```
[options]
packages = find:
```

in your setup.cfg?

**Comment by toumorokoshi** [comment]
Sorry about that! I've yanked the release for now.

I'll publish a new version later today.

**Comment by toumorokoshi** [comment]
1.0.1 is now released, and I've verified that the wheel does contain the files this time and installs as wheels on my projects.

Sorry about all the trouble this caused, please let me know if this doesn't fix you.
