### ISSUE TITLE
1.0.1 released on pypi.org but there is no tag from which it is created

### ISSUE THREAD

**Issue by dvzrv** [toumorokoshi/deepmerge#17]
Hi! I'm about to package this project for Arch Linux.

There seems to be no [tag in this repository](https://github.com/toumorokoshi/deepmerge/tags) for the 1.0.1 release on pypi.org (nor [any of the other recent releases](https://pypi.org/project/deepmerge/#history)).

Can you please push the recent history and tags? Thanks! :)

**Comment by toumorokoshi** [comment]
Hello! sorry about those missing tags.

Since I know those are needed for your Arch package (and thank you for adding it!), I'll use a GitHub release process that uses tags to trigger to ensure new tags will be there if you need them.

Hope that helps!
