### ISSUE TITLE
Add Type Hints

### ISSUE THREAD

**Issue by nhairs** [toumorokoshi/deepmerge#27]
It would be good if `deepmerge` added and exposed typing information so that calling libraries can check they are passing the correct types.

To support inline type hints would require dropping support for `python<3.5`, however given the [security support schedule](https://endoflife.date/python) it may be desirable to drop support up to `3.7`. [Checking PyPI Stats](https://pypistats.org/packages/deepmerge), versions `<=3.6` make up less than 1% of daily downloads.

**Comment by toumorokoshi** [comment]
Hi! I think it's a good time to do so - older versions of the packages will remain for those using older python versions anyway.

Id happily accept a PR that drops older python support as well as adds type hints.

**Comment by nhairs** [comment]
Heads up that I probably won't be looking to do a PR for this anytime soon. I'm currently working on a couple of large PRs (2K+, 6K+ lines added) for adding type annotations to other opensource projects, which is most of my spare time gone for the foreseeable future.
