### ISSUE TITLE
"Strategies are passed as a list, and the merge runs through each strategy sequentially"

### ISSUE THREAD

**Issue by brianthelion** [toumorokoshi/deepmerge#3]
From the README:
https://github.com/toumorokoshi/deepmerge/blob/68f64b094c1edaf7a26cf0c7a2c181c5a82555ee/README.rst#L63-L66

This is somewhat ambiguous as there are two ways to interpret it at a glance:

1. "The result is given by the first strategy to succeed." 
2. "The result is the composition of all the strategies."

From the source code, it's clear that ALL the strategies are applied, ie, (2).

https://github.com/toumorokoshi/deepmerge/blob/68f64b094c1edaf7a26cf0c7a2c181c5a82555ee/deepmerge/strategy/core.py#L32-L39

The README should be updated to increase clarity.

**Comment by toumorokoshi** [comment]
@brianthelion Thanks for the feedback! Yeah, I see that the readme isn't really descriptive enough.

Regarding the actual behavior, the strategies are indeed applied sequentially, although it does stop at the first one that returns a value that is not STRATEGY_END.

I've updated the readme to better clarify that. Can you take a look and see if that helps?

**Comment by toumorokoshi** [comment]
@brianthelion I'm closing this as fixed to keep the open issues to ones that actively need addressing. Feel free to reopen if you think there's still issues.

Thanks and happy new year!
